/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_;

import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author vicge
 */
public class Mostrar extends javax.swing.JFrame {

    public ArrayList<Empleado>lista_empleados;
    /**
     * Creates new form Registro
     */
    public Mostrar(ArrayList<Empleado>lista_empleados) {
        initComponents();
        this.lista_empleados = lista_empleados;
    }

    public Mostrar() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Nombre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Departamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Puesto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        jButton4.setText("Regresar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1)
                        .addGap(91, 91, 91)
                        .addComponent(jButton2)
                        .addGap(106, 106, 106)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(55, 55, 55)
                .addComponent(jButton4)
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del empleado a mostrar");
        if (nombre != null && !nombre.isEmpty()) {
            for (Empleado emp : lista_empleados) {
                if (emp.getNombre().equals(nombre)) {
                    TA.setText("");
                    TA.append("Nombre: " + emp.getNombre() + "\n");
                    TA.append("Apellido Paterno: " + emp.getApellidoPaterno() + "\n");
                    TA.append("Apellido Materno: " + emp.getApellidoMaterno() + "\n");
                    TA.append("Edad: " + String.valueOf(emp.getEdad()) + "\n");  // Convertir int a String
                    TA.append("Fecha de Nacimiento: " + emp.getFechaNacimiento() + "\n");
                    TA.append("Nombre de la Empresa: " + emp.getNombreEmpresa() + "\n");
                    TA.append("Giro de la Empresa: " + emp.getGiroEmpresa() + "\n");
                    TA.append("Fecha de Ingreso: " + emp.getFechaIngreso() + "\n");
                    TA.append("Clave del Empleado: " + emp.getClaveEmpleado() + "\n");
                    TA.append("Departamento: " + emp.getDepartamento() + "\n");
                    TA.append("Puesto: " + emp.getPuesto() + "\n");
                    TA.append("Horas Trabajadas: " + String.valueOf(emp.getHorasTrabajadas()) + "\n");  // Convertir int a String
                    TA.append("Pago por Hora: " + String.valueOf(emp.getPagoPorHora()) + "\n");
                    TA.append("Sueldo neto: " + String.valueOf(emp.calcularSueldoNeto()) + "\n");
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Empleado no encontrado.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String departamento = JOptionPane.showInputDialog(this, "Ingrese el departamento del empleado a mostrar");
        if (departamento != null && !departamento.isEmpty()) {
            for (Empleado emp : lista_empleados) {
                if (emp.getDepartamento().equals(departamento)) {
                    TA.setText("");
                    TA.append("Nombre: " + emp.getNombre() + "\n");
                    TA.append("Apellido Paterno: " + emp.getApellidoPaterno() + "\n");
                    TA.append("Apellido Materno: " + emp.getApellidoMaterno() + "\n");
                    TA.append("Edad: " + String.valueOf(emp.getEdad()) + "\n");  // Convertir int a String
                    TA.append("Fecha de Nacimiento: " + emp.getFechaNacimiento() + "\n");
                    TA.append("Nombre de la Empresa: " + emp.getNombreEmpresa() + "\n");
                    TA.append("Giro de la Empresa: " + emp.getGiroEmpresa() + "\n");
                    TA.append("Fecha de Ingreso: " + emp.getFechaIngreso() + "\n");
                    TA.append("Clave del Empleado: " + emp.getClaveEmpleado() + "\n");
                    TA.append("Departamento: " + emp.getDepartamento() + "\n");
                    TA.append("Puesto: " + emp.getPuesto() + "\n");
                    TA.append("Horas Trabajadas: " + String.valueOf(emp.getHorasTrabajadas()) + "\n");  // Convertir int a String
                    TA.append("Pago por Hora: " + String.valueOf(emp.getPagoPorHora()) + "\n"); 
                    TA.append("Sueldo neto: " + String.valueOf(emp.calcularSueldoNeto()) + "\n");
                    return;
                   
                }
            }
            JOptionPane.showMessageDialog(this, "Empleado no encontrado.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String puesto = JOptionPane.showInputDialog(this, "Ingrese el puesto del empleado a mostrar");
        if (puesto != null && !puesto.isEmpty()) {
            for (Empleado emp : lista_empleados) {
                if (emp.getPuesto().equals(puesto)) {
                    TA.setText("");
                    TA.append("Nombre: " + emp.getNombre() + "\n");
                    TA.append("Apellido Paterno: " + emp.getApellidoPaterno() + "\n");
                    TA.append("Apellido Materno: " + emp.getApellidoMaterno() + "\n");
                    TA.append("Edad: " + String.valueOf(emp.getEdad()) + "\n");  // Convertir int a String
                    TA.append("Fecha de Nacimiento: " + emp.getFechaNacimiento() + "\n");
                    TA.append("Nombre de la Empresa: " + emp.getNombreEmpresa() + "\n");
                    TA.append("Giro de la Empresa: " + emp.getGiroEmpresa() + "\n");
                    TA.append("Fecha de Ingreso: " + emp.getFechaIngreso() + "\n");
                    TA.append("Clave del Empleado: " + emp.getClaveEmpleado() + "\n");
                    TA.append("Departamento: " + emp.getDepartamento() + "\n");
                    TA.append("Puesto: " + emp.getPuesto() + "\n");
                    TA.append("Horas Trabajadas: " + String.valueOf(emp.getHorasTrabajadas()) + "\n");  // Convertir int a String
                    TA.append("Pago por Hora: " + String.valueOf(emp.getPagoPorHora()) + "\n"); 
                    TA.append("Sueldo neto: " + String.valueOf(emp.calcularSueldoNeto()) + "\n");
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Empleado no encontrado.");
        }    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
